artifact_uri: file:c:/Users/Joao Pedro/Desktop/projects/MLE_FIAP/exploracao_mvp/notebooks/../mlflow_tracking/554298265250474829/94e74557993a42d2839b7c931887ba91/artifacts
end_time: 1773975059503
entry_point_name: ''
experiment_id: '554298265250474829'
lifecycle_stage: active
run_id: 94e74557993a42d2839b7c931887ba91
run_name: Logistic Regression
source_name: ''
source_type: 4
source_version: ''
start_time: 1773975056559
status: 3
tags: []
user_id: Joao Pedro
