artifact_location: file:c:/Users/Joao Pedro/Desktop/projects/MLE_FIAP/exploracao_mvp/notebooks/../mlflow_tracking/554298265250474829
creation_time: 1773974965869
experiment_id: '554298265250474829'
last_update_time: 1773974965869
lifecycle_stage: active
name: churn_mvp
workspace: default
